'use strict';
const c=document.querySelector('#game'),x=c.getContext('2d'),W=1280,H=720;
const ui={score:q('#score'),status:q('#status'),mode:q('#modeLabel'),setup:q('#setup'),slots:q('#slots'),result:q('#result'),rt:q('#resultTitle'),rr:q('#resultText'),L:q('#leftHand'),R:q('#rightHand'),E:q('#enter'),S:q('#skill')};
function q(s){return document.querySelector(s)}
const TYPES={sword:{name:'剣＋盾',r:'sword',l:'shield',speed:180},spear:{name:'槍＋盾',r:'spear',l:'shield',speed:165},dagger:{name:'短剣二刀流',r:'daggerR',l:'daggerL',speed:210},doubleShield:{name:'双盾',r:'dualShield',l:'dualShield',speed:130}};
let formation=['sword','spear','dagger'],mode='field',blue=0,red=0,roundOver=0,last=performance.now(),keys={},joy={id:null,dx:0,dy:0},actors=[],effects=[];
const obstacles=[{x:465,y:115,w:95,h:180},{x:465,y:425,w:95,h:180},{x:720,y:250,w:100,h:220}];
for(let i=0;i<3;i++){let d=document.createElement('div');d.className='slot';d.innerHTML=`<b>選手 ${i+1}</b><select data-i="${i}">${Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${formation[i]===k?'selected':''}>${v.name}</option>`).join('')}</select>`;ui.slots.append(d)}
ui.slots.onchange=e=>{if(e.target.dataset.i!=null)formation[+e.target.dataset.i]=e.target.value};
q('#start').onclick=()=>{ui.setup.classList.add('hidden');startMatch()};q('#back').onclick=()=>{ui.setup.classList.add('hidden');mode='field'};q('#rematch').onclick=()=>{ui.result.classList.add('hidden');startMatch()};q('#fieldBack').onclick=()=>{ui.result.classList.add('hidden');mode='field';ui.mode.textContent='FIELD';ui.status.textContent='フィールドを歩いて競技場へ'};
function unit(team,i,type){let bx=team===0?245:1035;return {team,i,type,x:bx+(i%2)*45*(team? -1:1),y:260+i*100,r:25,alive:true,face:team?Math.PI:0,cd:0,stun:0,shield:false,shieldA:0,ai:team===1||i>0};}
function resetRound(){actors=[];formation.forEach((t,i)=>actors.push(unit(0,i,t)));['sword','spear','dagger'].forEach((t,i)=>actors.push(unit(1,i,t)));roundOver=0;effects=[];syncButtons()}
function startMatch(){mode='match';blue=red=0;ui.mode.textContent='MATCH';ui.score.textContent='0 - 0';resetRound();ui.status.textContent='敵拠点を取るか、全員OUTで勝利'}
function controlled(){return actors.find(a=>a.team===0&&a.alive&&!a.ai)||null}
function transfer(){let n=actors.find(a=>a.team===0&&a.alive);if(n){actors.filter(a=>a.team===0).forEach(a=>a.ai=true);n.ai=false;syncButtons()}}
function syncButtons(){let a=controlled();if(!a)return;let t=TYPES[a.type];ui.R.querySelector('small').innerHTML=label(t.r);ui.L.querySelector('small').innerHTML=label(t.l)}
function label(v){return ({sword:'剣',spear:'槍',shield:'盾',daggerR:'右短剣',daggerL:'左短剣',dualShield:'両盾'})[v]||v}
function nearestEnemy(a){let es=actors.filter(b=>b.alive&&b.team!==a.team);return es.sort((p,q)=>dist(a,p)-dist(a,q))[0]}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function angle(a,b){return Math.atan2(b.y-a.y,b.x-a.x)}
function norm(v){while(v>Math.PI)v-=Math.PI*2;while(v<-Math.PI)v+=Math.PI*2;return v}
function hand(a,side,down=true){if(!a||!a.alive||a.stun>0)return;let kind=TYPES[a.type][side];if(kind==='shield'||kind==='dualShield'){a.shield=down;if(down){let e=nearestEnemy(a);if(e)a.shieldA=angle(a,e)}return}if(!down||a.cd>0)return;let e=nearestEnemy(a);if(e)a.face=angle(a,e);attack(a,kind);a.cd=kind.startsWith('dagger')?.28:kind==='spear'?.62:.5}
function attack(a,kind){let range=kind==='spear'?135:kind.startsWith('dagger')?62:92,arc=kind==='spear'?.22:kind.startsWith('dagger')?.72:1.55;effects.push({kind:'swing',x:a.x,y:a.y,a:a.face,range,arc,t:.16,team:a.team});let hit=[];for(let b of actors){if(!b.alive||b.team===a.team)continue;let d=dist(a,b),da=Math.abs(norm(angle(a,b)-a.face));if(d<=range+b.r&&da<=arc/2)hit.push(b)}
for(let b of hit){if(blocked(b,a)){a.stun=.42;effects.push({kind:'block',x:b.x,y:b.y,t:.25});continue}let clash=actors.find(o=>o!==a&&o.team!==a.team&&o.alive&&o.cd>.18&&dist(a,o)<70);if(clash){a.stun=.2;clash.stun=.2;continue}b.alive=false;effects.push({kind:'out',x:b.x,y:b.y,t:.55});if(!b.ai)transfer()}}
function blocked(def,atk){if(!def.shield)return false;let dual=TYPES[def.type].r==='dualShield';let aa=angle(def,atk);if(dual)return true;return Math.abs(norm(aa-def.shieldA))<1.12}
function move(a,vx,vy,dt){let sp=TYPES[a.type].speed*(a.shield?(a.type==='doubleShield'?.42:.62):1);let nx=a.x+vx*sp*dt,ny=a.y+vy*sp*dt;nx=Math.max(215,Math.min(1065,nx));ny=Math.max(95,Math.min(625,ny));if(!obstacles.some(o=>nx+a.r>o.x&&nx-a.r<o.x+o.w&&ny+a.r>o.y&&ny-a.r<o.y+o.h)){a.x=nx;a.y=ny}}
function ai(a,dt){let es=actors.filter(b=>b.alive&&b.team!==a.team),e=es.sort((p,q)=>dist(a,p)-dist(a,q))[0];if(!e)return;let enemyBase=a.team?{x:235,y:360}:{x:1045,y:360},target=e;let alliesNear=actors.filter(b=>b.alive&&b.team===a.team&&dist(a,b)<170).length;if(dist(a,e)>220||alliesNear>1)target=enemyBase;let ang=angle(a,target),d=dist(a,e);a.face=angle(a,e);let t=TYPES[a.type];if((t.l==='shield'||t.l==='dualShield')&&d<125&&Math.random()<.06){a.shield=true;a.shieldA=angle(a,e)}else if(d>95)a.shield=false;if(d<(a.type==='spear'?140:a.type==='dagger'?70:100)&&a.cd<=0&&!a.shield)hand(a,'r',true);else move(a,Math.cos(ang),Math.sin(ang),dt)}
function update(dt){if(mode!=='match'||roundOver)return;for(let a of actors){if(!a.alive)continue;a.cd=Math.max(0,a.cd-dt);a.stun=Math.max(0,a.stun-dt);if(a.ai&&a.stun<=0)ai(a,dt)}let p=controlled();if(p&&p.stun<=0){let vx=joy.dx+(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),vy=joy.dy+(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0),m=Math.hypot(vx,vy);if(m>1){vx/=m;vy/=m}move(p,vx,vy,dt)}
let ba=actors.filter(a=>a.team===0&&a.alive),ra=actors.filter(a=>a.team===1&&a.alive);if(!ra.length)winRound(0,'敵チーム全員OUT');else if(!ba.length)winRound(1,'味方チーム全員OUT');else{if(ba.some(a=>Math.hypot(a.x-1045,a.y-360)<42))winRound(0,'敵拠点を奪取');if(ra.some(a=>Math.hypot(a.x-235,a.y-360)<42))winRound(1,'自陣拠点を奪取された')}effects.forEach(e=>e.t-=dt);effects=effects.filter(e=>e.t>0)}
function winRound(team,why){if(roundOver)return;roundOver=1;team===0?blue++:red++;ui.score.textContent=`${blue} - ${red}`;ui.status.textContent=(team===0?'BLUE ':'RED ')+why;if(blue>=2||red>=2)setTimeout(()=>{ui.rt.textContent=blue>red?'勝利！':'敗北';ui.rr.textContent=`${blue} - ${red}　${why}`;ui.result.classList.remove('hidden')},700);else setTimeout(resetRound,850)}
function draw(){x.clearRect(0,0,W,H);if(mode==='field')drawField();else drawMatch()}
function drawField(){x.fillStyle='#9dc985';x.fillRect(0,0,W,H);x.fillStyle='#d6c895';x.beginPath();x.moveTo(120,600);x.quadraticCurveTo(500,370,650,350);x.quadraticCurveTo(880,310,1160,130);x.lineWidth=90;x.strokeStyle='#d8cba2';x.stroke();place(260,190,'クラブハウス','🏠');place(710,330,'競技場','🏟');place(1040,150,'森の練習路','🌳');x.fillStyle='#24483b';x.font='bold 28px sans-serif';x.fillText('けもの競技村',55,65);x.font='18px sans-serif';x.fillText('※ フィールドマップは近接版用の仮デザイン',55,94);let px=600+Math.sin(performance.now()/900)*10;x.font='50px sans-serif';x.fillText('🐸',px,470);x.font='16px sans-serif';x.fillText('競技場の「入」で編成へ',530,510)}
function place(px,py,n,ico){x.font='70px sans-serif';x.fillText(ico,px,py);x.font='bold 20px sans-serif';x.fillStyle='#26493d';x.fillText(n,px-10,py+34)}
function drawMatch(){x.fillStyle='#b8d89a';x.fillRect(0,0,W,H);x.fillStyle='#d8c99c';x.fillRect(190,70,900,580);x.strokeStyle='#496d54';x.lineWidth=6;x.strokeRect(190,70,900,580);x.setLineDash([12,12]);x.beginPath();x.moveTo(640,70);x.lineTo(640,650);x.stroke();x.setLineDash([]);for(let o of obstacles){x.fillStyle='#6f8061';x.fillRect(o.x,o.y,o.w,o.h);x.fillStyle='#8e9b78';x.fillRect(o.x+8,o.y+8,o.w-16,o.h-16)}base(235,360,'#4d83dc');base(1045,360,'#d65a5f');for(let a of actors)drawActor(a);for(let e of effects)drawEffect(e)}
function base(px,py,col){x.strokeStyle=col;x.lineWidth=8;x.beginPath();x.arc(px,py,35,0,Math.PI*2);x.stroke();x.globalAlpha=.2;x.fillStyle=col;x.fill();x.globalAlpha=1}
function drawActor(a){if(!a.alive)return;x.save();x.translate(a.x,a.y);x.rotate(a.face);x.fillStyle=a.team?'#e36b68':'#5488df';x.beginPath();x.arc(0,0,a.r,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.beginPath();x.arc(8,-9,6,0,Math.PI*2);x.fill();x.fillStyle='#223';x.beginPath();x.arc(10,-9,2,0,Math.PI*2);x.fill();let t=TYPES[a.type];drawWeapon(t.r,1,a.shield);drawWeapon(t.l,-1,a.shield);if(a===controlled()){x.strokeStyle='#fff';x.lineWidth=3;x.beginPath();x.arc(0,0,32,0,Math.PI*2);x.stroke()}x.restore();x.fillStyle='#18382f';x.font='12px sans-serif';x.textAlign='center';x.fillText(TYPES[a.type].name,a.x,a.y+43);x.textAlign='start'}
function drawWeapon(k,side,active){x.strokeStyle='#f5efe0';x.lineWidth=8;x.lineCap='round';if(k==='shield'||k==='dualShield'){x.strokeStyle=active?'#fff6b5':'#dbe7d4';x.lineWidth=10;x.beginPath();x.arc(16,side*18,16,-1.1,1.1);x.stroke()}else{x.beginPath();x.moveTo(15,side*13);x.lineTo(k==='spear'?62:45,side*(k.startsWith('dagger')?18:20));x.stroke()}}
function drawEffect(e){x.save();x.globalAlpha=Math.min(1,e.t*5);if(e.kind==='swing'){x.strokeStyle=e.team?'#ff9c9c':'#d8efff';x.lineWidth=12;x.beginPath();x.arc(e.x,e.y,e.range,e.a-e.arc/2,e.a+e.arc/2);x.stroke()}else{x.font='bold 26px sans-serif';x.fillStyle=e.kind==='block'?'#fff':'#3c3028';x.fillText(e.kind==='block'?'BLOCK!':'OUT!',e.x-28,e.y-38)}x.restore()}
function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='j')hand(controlled(),'l',true);if(e.key==='k')hand(controlled(),'r',true)});addEventListener('keyup',e=>{keys[e.key]=false;if(e.key==='j')hand(controlled(),'l',false)});
function bind(btn,side){btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);hand(controlled(),side,true)});btn.addEventListener('pointerup',e=>{e.preventDefault();hand(controlled(),side,false)});btn.addEventListener('pointercancel',()=>hand(controlled(),side,false))}bind(ui.L,'l');bind(ui.R,'r');
ui.E.onclick=()=>{if(mode==='field'){ui.setup.classList.remove('hidden');ui.status.textContent='3人の装備を選択'}};ui.S.onclick=()=>{ui.status.textContent='スキル枠：後でバランスを見ながら実装予定'};
const stick=q('#stick'),knob=stick.querySelector('i');function joyMove(e){let r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=(e.clientX-cx)/(r.width*.35),dy=(e.clientY-cy)/(r.height*.35),m=Math.hypot(dx,dy);if(m>1){dx/=m;dy/=m}joy.dx=dx;joy.dy=dy;knob.style.transform=`translate(${dx*30}px,${dy*30}px)`}stick.onpointerdown=e=>{joy.id=e.pointerId;stick.setPointerCapture(e.pointerId);joyMove(e)};stick.onpointermove=e=>{if(e.pointerId===joy.id)joyMove(e)};function joyEnd(){joy.id=null;joy.dx=joy.dy=0;knob.style.transform=''}stick.onpointerup=joyEnd;stick.onpointercancel=joyEnd;
